// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn8DupP59H5lyTcoVLa2Yoq25-Rx0BnDE',
    appId: '1:427362740894:web:d60b3f62b04b5275b0298f',
    messagingSenderId: '427362740894',
    projectId: 'reem-66ca2',
    authDomain: 'reem-66ca2.firebaseapp.com',
    storageBucket: 'reem-66ca2.appspot.com',
    measurementId: 'G-X9VDQS0QXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFi7-2REiQZkwGEI_tve5ZL4Z-slRdBfs',
    appId: '1:427362740894:android:55dee12854b5bc8cb0298f',
    messagingSenderId: '427362740894',
    projectId: 'reem-66ca2',
    storageBucket: 'reem-66ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXSdIfBpyHGsJj06AfqgCTTb22UghCTk',
    appId: '1:427362740894:ios:c8429f77e38fc62bb0298f',
    messagingSenderId: '427362740894',
    projectId: 'reem-66ca2',
    storageBucket: 'reem-66ca2.appspot.com',
    iosBundleId: 'com.example.firbaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXSdIfBpyHGsJj06AfqgCTTb22UghCTk',
    appId: '1:427362740894:ios:0ed9f296e06ebe36b0298f',
    messagingSenderId: '427362740894',
    projectId: 'reem-66ca2',
    storageBucket: 'reem-66ca2.appspot.com',
    iosBundleId: 'com.example.firbaseproject.RunnerTests',
  );
}
